config:
  validation: true
  warningsAsErrors: true

complexity:
  CyclomaticComplexMethod:
    ignoreSimpleWhenEntries: true
  LongMethod:
    excludes:
      - '**/presentation/screens/MainScreen.kt'
      - '**/test/**'
      - '**/androidTest/**'
  LongParameterList:
    ignoreAnnotated:
      - Composable
    excludes:
      - '**/data/remote/WeatherApiService.kt'
      - '**/data/repository/WeatherRepositoryImpl.kt'
      - '**/test/**'
      - '**/androidTest/**'
  TooManyFunctions:
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
  LargeClass:
    excludes:
      - '**/test/**'
      - '**/androidTest/**'

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
    excludes:
      - '**/test/**'
      - '**/androidTest/**'

style:
  MagicNumber:
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '8'
      - '16'
      - '24'
      - '0.8'
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreNamedArgument: true
    ignoreEnums: true
    ignoreRanges: true
    excludes:
      - '**/domain/model/WeatherCondition.kt'
      - '**/test/**'
      - '**/androidTest/**'
  MaxLineLength:
    active: false
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    excludeGuardClauses: true
    excludes:
      - '**/data/local/SavedLocationLocalDataSource.kt'
  ThrowsCount:
    excludeGuardClauses: true
    excludes:
      - '**/domain/usecase/GetCurrentLocationUseCase.kt'
  WildcardImport:
    active: false
